<%@ Page Language="C#" Title="Category" AutoEventWireup="true" MasterPageFile="~/MasterPage.master" CodeFile="Category.aspx.cs" Inherits="Category" %>

<asp:Content ID="Content" ContentPlaceHolderID="Body" Runat="Server">
    <div class="container">
        
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                           SelectCommand="SELECT Category.Title, Category.Description from Category" 
                           DeleteCommand="DELETE FROM [Category] WHERE [Id] = @Id" 
                           UpdateCommand="UPDATE [Category] SET [Title] = @Title, [Description] = @Description WHERE [Id] = @Id">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="Title" Type="String" />
                <asp:Parameter Name="Description" Type="String" />
                <asp:Parameter Name="Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="Titlu" HeaderText="Titlu" SortExpression="Titlu" />
                <asp:BoundField DataField="Autor" HeaderText="Autor" SortExpression="Autor" />
                <asp:BoundField DataField="Data" HeaderText="Data" SortExpression="Data" />
                <asp:BoundField DataField="Nr_Pagini" HeaderText="Numar Pagini" SortExpression="Nr_Pagini" />
                <asp:BoundField DataField="Descriere" HeaderText="Descriere" SortExpression="Descriere" />
                <asp:BoundField DataField="Denumire" HeaderText="Editura" SortExpression="Denumire" />
                <asp:HyperLinkField DataNavigateUrlFields="Id" DataNavigateUrlFormatString="~/Editare.aspx?id={0}" HeaderText="Edit" Text="Edit" />
                <asp:HyperLinkField DataNavigateUrlFields="Id" DataNavigateUrlFormatString="~/Stergere.aspx?id={0}" HeaderText="Delete" Text="Delete" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        </div>
</asp:Content>